layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 5
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: GIS
    web_url: https://arcg.is/0GuDvX
    image_url: https://www.esri.com/content/dam/esrisites/en-us/arcgis/what-is-gis/images/overview-how-maps.png

  - name: Integrating GIS with Web Applications
    web_url: https://arcg.is/1eH9Wu
    image_url: https://www.townoflisbonwi.com/wp-content/uploads/2020/08/Depositphotos_159548126_s-2019-495x400.jpg

  - name: Neural Networks
    web_url: https://keras.io/api/applications/densenet/
    image_url: https://www.genengnews.com/wp-content/uploads/2020/07/Jul24_GettyImages-582759294_neurons-scaled.jpg
